apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-nodeport
  labels:
    k8s-app: expense-tracker
spec:
  selector:
    k8s-app: expense-tracker
  type: NodePort
  ports:
    - port: 5000
